[package]
name = "bffextract"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.12", features = ["derive"] }
comfy-table = { version = "7.1.0", default-features = false }
file-mode = "0.1.2"
filetime = "0.2.23"
normalize-path = "0.2.1"

[target.'cfg(unix)'.dependencies]
users = { version = "0.11.0", default-features = false, features = ["cache"] }
