use crate::Result;
use std::io::Read;

/// All BFF files should contain this magic number.
pub const FILE_MAGIC: u32 = 0xea6b0009; //0x09006BEA;
/// A compressed record should contain this magic number.
pub const HUFFMAN_MAGIC: u16 = 0xEA6C;
/// All records should contain one of these magic numbers.
pub const HEADER_MAGICS: [u16; 3] = [0xEA6B, HUFFMAN_MAGIC, 0xEA6D];

/// Representation of the file header.
///
/// Some data is not identified at the moment and named "unk*"
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct FileHeader {
    /// Magic number
    pub magic: u32,
    /// Archive checksum written by the AIX backup producer.
    pub checksum: u32,
    /// Archive creation time.
    pub current_date: u32,
    /// Start time of the backup run. In sampled single-volume archives this matches `current_date`.
    pub starting_date: u32,
    /// Constant sentinel in sampled archives (`0x7FFF_FFFF`). Likely a legacy limit or "unbounded" marker.
    pub unk10: u32,
    /// Backup mode string, typically `by name`.
    pub disk_name: [u8; 8],
    /// Reserved, observed as 0.
    pub unk1_c: u32,
    /// Reserved, observed as 0.
    pub unk20: u32,
    /// Backup mode string, typically `by name`.
    pub filesystem_name: [u8; 8],
    /// Reserved, observed as 0.
    pub unk2_c: u32,
    /// Reserved, observed as 0.
    pub unk30: u32,
    /// Typically contains the username of the build user.
    pub username: [u8; 8],
    /// Reserved, observed as 0.
    pub unk3_c: u32,
    /// Reserved, observed as 0.
    pub unk40: u32,
    /// Constant `100` in sampled archives. Likely a format or writer version field.
    pub unk44: u32,
}

impl FileHeader {
    /// Returns the 16-bit archive header checksum validated by AIX `restbyname`.
    pub fn stored_checksum(&self) -> u16 {
        (self.checksum & 0xFFFF) as u16
    }

    /// Returns the constant sentinel stored at offset `0x10`.
    ///
    /// The exact AIX field name is still unknown, so this accessor keeps a
    /// conservative semantic name while avoiding direct dependence on `unk10`.
    pub fn archive_limit_marker(&self) -> u32 {
        self.unk10
    }

    /// Returns the archive writer / format revision field stored at offset `0x44`.
    pub fn format_version(&self) -> u32 {
        self.unk44
    }
}

/// Compute the AIX archive-header checksum for a raw file-header block.
///
/// The block length is encoded in the first byte as a count of 8-byte units.
/// AIX `restbyname` validates only the low 16 bits stored at offset `0x04..0x05`.
pub(crate) fn compute_file_header_checksum(block: &[u8]) -> Option<u16> {
    let block_units = *block.first()? as usize;
    let block_len = block_units.checked_mul(8)?;
    if block_len == 0 || block_len > block.len() || block_len < 6 {
        return None;
    }

    let mut sum = 0u32;
    for (index, byte) in block[..block_len].iter().copied().enumerate() {
        let value = if matches!(index, 4 | 5) {
            0
        } else {
            u32::from(byte)
        };
        sum = (sum + ((value << (value & 0x07)) & 0xFFFF)) & 0xFFFF;
    }

    Some(sum as u16)
}

/// Represntation of a record header.
///
/// Some data is not identified at the moment and named "unk*"
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct RecordHeader {
    /// Entry subtype byte emitted by the AIX backup writer.
    ///
    /// This varies across directories, regular files, symlinks, and package metadata records,
    /// but is not required for extraction because `mode` carries the actual Unix file type.
    pub unk00: u8,
    /// Record format marker. Normal entries use `0x0B`; `0x07` appears in some offset records.
    pub unk01: u8,
    /// Magic number
    pub magic: u16,
    /// Per-entry identifier generated by the writer, likely inode or backup catalog metadata.
    pub unk04: u32,
    /// Directory identifier / parent linkage field.
    ///
    /// Sampled directories carry descending negative values (`0xFFFF_FFFF`, `0xFFFF_FFFE`, ...),
    /// while regular files use 0.
    pub unk08: u32,
    /// File mode (rwx...) as bit represntation
    pub mode: u32,
    /// User ID number of the file
    pub uid: u32,
    /// Group ID number of the file
    pub gid: u32,
    /// File size
    pub size: u32,
    /// Last access timestamp of the file.
    pub atime: u32,
    /// Last modified timestamp of the file
    pub mtime: u32,
    /// Inode status-change timestamp (`ctime`).
    pub time24: u32,
    /// Archive-wide filesystem/device metadata word.
    ///
    /// This is constant across all records in sampled archives but differs between archives.
    pub unk28: u32,
    /// Archive-wide filesystem/device metadata word.
    ///
    /// This is constant across all records in sampled archives but differs between archives.
    pub unk2_c: u32,
    /// Reserved, observed as 0.
    pub unk30: u32,
    /// Reserved, observed as 0.
    pub unk34: u32,
    /// Stored payload size in the archive.
    ///
    /// Equals `size` for raw records and is smaller when `magic == HUFFMAN_MAGIC`.
    pub compressed_size: u32,
    /// Reserved, observed as 0.
    pub unk3_c: u32,
}

impl RecordHeader {
    /// Returns the entry subtype byte emitted by the AIX backup writer.
    pub fn entry_subtype(&self) -> u8 {
        self.unk00
    }

    /// Returns the record format marker.
    pub fn format_marker(&self) -> u8 {
        self.unk01
    }

    /// Returns the per-entry identifier written into the record header.
    pub fn entry_id(&self) -> u32 {
        self.unk04
    }

    /// Returns the directory identifier / parent linkage field.
    pub fn directory_id(&self) -> u32 {
        self.unk08
    }

    /// Returns the inode status-change timestamp (`ctime`).
    pub fn change_time(&self) -> u32 {
        self.time24
    }

    /// Returns the first archive-wide metadata word carried in each record header.
    pub fn archive_metadata_word_1(&self) -> u32 {
        self.unk28
    }

    /// Returns the second archive-wide metadata word carried in each record header.
    pub fn archive_metadata_word_2(&self) -> u32 {
        self.unk2_c
    }
}

impl Default for RecordHeader {
    fn default() -> Self {
        Self {
            unk00: 0,
            unk01: 0,
            magic: 0,
            unk04: 0,
            unk08: 0,
            mode: 0o644,
            uid: 0,
            gid: 0,
            size: 0,
            atime: 0,
            mtime: 0,
            time24: 0,
            unk28: 0,
            unk2_c: 0,
            unk30: 0,
            unk34: 0,
            compressed_size: 0,
            unk3_c: 0,
        }
    }
}

/// Read string from stream until NULL.
pub(crate) fn read_aligned_string<R: ?Sized + Read>(reader: &mut R) -> Result<String> {
    let mut result: Vec<u8> = vec![];
    loop {
        let mut data = [0; 8];
        let len = reader.read(&mut data)?;
        if len == 0 {
            let s = String::from_utf8_lossy(&result);
            return Ok(first_segment(&s));
        }
        for c in data {
            if c == 0 {
                let s = String::from_utf8_lossy(&result);
                return Ok(first_segment(&s));
            }
            result.push(c);
        }
    }
}

/// Get the first segment of a string until a newline, tab, or vertical tab.
fn first_segment(text: &str) -> String {
    if let Some(index) = text.find(|c| matches!(c, '\n' | '\t' | '\x0B' | '\x7F')) {
        text[..index].to_string()
    } else {
        text.to_string()
    }
}

#[cfg(test)]
mod tests {
    use std::io::Cursor;

    use super::*;

    #[test]
    fn read_aligned_string_default() {
        let mut reader = Cursor::new([97, 98, 99, 0, 1, 2, 3, 4]);
        let result = read_aligned_string(&mut reader).expect("Could not read aligned string.");
        assert_eq!(result, "abc");
    }

    #[test]
    fn read_aligned_string_double() {
        let mut reader = Cursor::new([97, 98, 99, 0, 1, 2, 3, 4, 97, 98, 99, 0, 1, 2, 3, 4]);
        let result = read_aligned_string(&mut reader).expect("Could not read aligned string.");
        assert_eq!(result, "abc");
    }

    #[test]
    fn read_aligned_string_long() {
        let mut reader = Cursor::new([
            97, 98, 99, 100, 101, 102, 103, 104, 97, 98, 99, 0, 1, 2, 3, 4,
        ]);
        let result = read_aligned_string(&mut reader).expect("Could not read aligned string.");
        assert_eq!(result, "abcdefghabc");
    }

    #[test]
    fn read_aligned_string_no_null() {
        let mut reader = Cursor::new([97, 98, 99, 1, 1, 2, 3, 4]);
        let result = read_aligned_string(&mut reader).expect("Could not read aligned string.");
        assert_eq!(result, "abc\u{1}\u{1}\u{2}\u{3}\u{4}");
    }

    #[test]
    fn read_aligned_string_stops_at_delete_marker() {
        let mut reader = Cursor::new([97, 99, 108, 47, 127, 127, 0, 0]);
        let result = read_aligned_string(&mut reader).expect("Could not read aligned string.");
        assert_eq!(result, "acl/");
    }

    #[test]
    fn read_aligned_string_no_8byte() {
        let mut reader = Cursor::new([97, 98, 99, 1, 1, 2, 3]);
        let result = read_aligned_string(&mut reader).expect("Could not read aligned string.");
        assert_eq!(result, "abc\u{1}\u{1}\u{2}\u{3}");
    }

    #[test]
    fn file_header_semantic_accessors() {
        let header = FileHeader {
            checksum: 0x0001_fb74,
            unk10: 0x7fff_ffff,
            unk44: 100,
            ..unsafe { std::mem::zeroed() }
        };

        assert_eq!(header.stored_checksum(), 0xfb74);
        assert_eq!(header.archive_limit_marker(), 0x7fff_ffff);
        assert_eq!(header.format_version(), 100);
    }

    #[test]
    fn compute_file_header_checksum_matches_sample_header() {
        let archive = include_bytes!("../../resources/test/test.bff");

        assert_eq!(compute_file_header_checksum(&archive[..72]), Some(0xfb74));
    }

    #[test]
    fn record_header_semantic_accessors() {
        let header = RecordHeader {
            unk00: 0x0f,
            unk01: 0x0b,
            unk04: 1234,
            unk08: u32::MAX,
            time24: 1_716_804_102,
            unk28: 0x24,
            unk2_c: 0x01,
            ..Default::default()
        };

        assert_eq!(header.entry_subtype(), 0x0f);
        assert_eq!(header.format_marker(), 0x0b);
        assert_eq!(header.entry_id(), 1234);
        assert_eq!(header.directory_id(), u32::MAX);
        assert_eq!(header.change_time(), 1_716_804_102);
        assert_eq!(header.archive_metadata_word_1(), 0x24);
        assert_eq!(header.archive_metadata_word_2(), 0x01);
    }
}
